"""empty message

Revision ID: 363b54321ed3
Revises: 97d4d234f874
Create Date: 2022-01-27 21:35:42.053325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363b54321ed3'
down_revision = '97d4d234f874'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hash_pass', sa.String(length=64), nullable=True))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('user', 'hash_pass')
    # ### end Alembic commands ###
